/**
 * The ENUM macro in enums.h.
 *
 * Every enum CStreamSettings exposes is generated by this one macro, and the
 * JSON layer, the key/value layer and the human-readable dump each pick a
 * DIFFERENT one of its three string accessors. Those three are not
 * interchangeable, so the asymmetries between them are pinned here rather than
 * rediscovered from a mis-parsed settings file:
 *
 *   name()       -> the enumerator identifier, e.g. "BIT_16". Written by
 *                   toJson() and getValue(), and the ONLY form from_string()
 *                   accepts. name()/from_string() is the round trip that works.
 *   to_string()  -> the second element of each pair in the ENUM declaration,
 *                   verbatim, e.g. "16 Bit". Used only by toString().
 *   values()     -> the numeric values, which need not be 0..count-1: DACRepeat
 *                   declares -1, -2, 0.
 */

#include <gtest/gtest.h>

#include <set>
#include <stdexcept>
#include <string>
#include <type_traits>

#include "settings_lib/stream_settings.h"

namespace {

using DataFormat = CStreamSettings::DataFormat;
using Resolution = CStreamSettings::Resolution;
using DACRepeat = CStreamSettings::DACRepeat;
using Attenuator = CStreamSettings::Attenuator;
using State = CStreamSettings::State;

// True only if `a == b` compiles for the given pair of operand types. Every
// combination below has to be usable: an ambiguous overload set makes these
// false and the test names say which combination broke.
template <typename A, typename B, typename = void>
struct IsComparable : std::false_type {};

template <typename A, typename B>
struct IsComparable<A, B, std::void_t<decltype(std::declval<A>() == std::declval<B>())>> : std::true_type {};

}  // namespace

// count is `static constexpr`, so it is implicitly inline and can be bound to a
// reference. EXPECT_EQ takes both operands by const reference, so every line in
// this test is also the check that it links at all: before the fix these were
// undefined references.
TEST(Enums, CountMatchesTheDeclaredEnumeratorsAndIsOdrUsable) {
    EXPECT_EQ(DataFormat::count, 3u);
    EXPECT_EQ(Resolution::count, 2u);
    EXPECT_EQ(DACRepeat::count, 3u);
    EXPECT_EQ(Attenuator::count, 2u);
    EXPECT_EQ(State::count, 2u);
    EXPECT_EQ(CStreamSettings::AC_DC::count, 2u);
    EXPECT_EQ(CStreamSettings::DataType::count, 2u);
    EXPECT_EQ(CStreamSettings::PassMode::count, 2u);
    EXPECT_EQ(CStreamSettings::DACPassMode::count, 2u);
    EXPECT_EQ(CStreamSettings::DACGain::count, 2u);
    EXPECT_EQ(CStreamSettings::ADCCaptureTime::count, 2u);
}

TEST(Enums, NameReturnsTheEnumeratorIdentifier) {
    EXPECT_STREQ(DataFormat(DataFormat::WAV).name(), "WAV");
    EXPECT_STREQ(DataFormat(DataFormat::TDMS).name(), "TDMS");
    EXPECT_STREQ(DataFormat(DataFormat::BIN).name(), "BIN");
    EXPECT_STREQ(Resolution(Resolution::BIT_8).name(), "BIT_8");
    EXPECT_STREQ(Resolution(Resolution::BIT_16).name(), "BIT_16");
    EXPECT_STREQ(DACRepeat(DACRepeat::DAC_REP_INF).name(), "DAC_REP_INF");
}

TEST(Enums, FromStringAcceptsTheIdentifierAndOnlyTheIdentifier) {
    EXPECT_EQ(DataFormat::from_string("WAV"), DataFormat::WAV);
    EXPECT_EQ(DataFormat::from_string("TDMS"), DataFormat::TDMS);
    // The display string is NOT accepted, even though to_string() produces it.
    EXPECT_THROW(DataFormat::from_string("wav"), std::invalid_argument);
    EXPECT_THROW(DataFormat::from_string(""), std::invalid_argument);
    EXPECT_THROW(DataFormat::from_string("Wav"), std::invalid_argument);
    EXPECT_THROW(DataFormat::from_string("WAV "), std::invalid_argument);
}

TEST(Enums, NameAndFromStringRoundTripForEveryEnumerator) {
    for (size_t i = 0; i < DataFormat::count; i++) {
        const DataFormat value = static_cast<DataFormat::_enumerated>(DataFormat::values()[i]);
        EXPECT_EQ(DataFormat::from_string(value.name()), value.value) << "index " << i;
    }
    for (size_t i = 0; i < DACRepeat::count; i++) {
        const DACRepeat value = static_cast<DACRepeat::_enumerated>(DACRepeat::values()[i]);
        EXPECT_EQ(DACRepeat::from_string(value.name()), value.value) << "index " << i;
    }
}

// names() has to cut each entry at the first separator, because STRINGIZE keeps
// the initialiser with it ("WAV = 0"). strings() must NOT: the display strings
// are free text. The same trim used to be applied to both, which turned
// Resolution's "8 Bit" into "8" - the only declaration with a space in it today.
TEST(Enums, TheDisplayStringIsTheDeclaredTextVerbatim) {
    EXPECT_STREQ(Resolution(Resolution::BIT_8).to_string(), "8 Bit");
    EXPECT_STREQ(Resolution(Resolution::BIT_16).to_string(), "16 Bit");
    // ... while the identifiers are still cut at the "=".
    EXPECT_STREQ(Resolution(Resolution::BIT_8).name(), "BIT_8");
    EXPECT_STREQ(Resolution(Resolution::BIT_16).name(), "BIT_16");
    EXPECT_STREQ(DataFormat(DataFormat::WAV).to_string(), "wav");
    EXPECT_STREQ(Attenuator(Attenuator::A_1_20).to_string(), "1:20");
    EXPECT_STREQ(DACRepeat(DACRepeat::DAC_REP_INF).to_string(), "Infinity");
    EXPECT_STREQ(CStreamSettings::PassMode(CStreamSettings::PassMode::NET).to_string(), "Network");
}

TEST(Enums, ValuesNeedNotBeContiguousOrPositive) {
    ASSERT_EQ(DACRepeat::count, 3u);
    EXPECT_EQ(DACRepeat::values()[0], -1);  // DAC_REP_OFF
    EXPECT_EQ(DACRepeat::values()[1], -2);  // DAC_REP_INF
    EXPECT_EQ(DACRepeat::values()[2], 0);   // DAC_REP_ON
    EXPECT_EQ(static_cast<int>(DACRepeat::DAC_REP_OFF), -1);
    EXPECT_EQ(static_cast<int>(DACRepeat::DAC_REP_INF), -2);
    EXPECT_EQ(static_cast<int>(DACRepeat::DAC_REP_ON), 0);
}

TEST(Enums, IsValidAcceptsDeclaredValuesOnly) {
    EXPECT_TRUE(DACRepeat::IsValid(-1));
    EXPECT_TRUE(DACRepeat::IsValid(-2));
    EXPECT_TRUE(DACRepeat::IsValid(0));
    EXPECT_FALSE(DACRepeat::IsValid(1));
    EXPECT_FALSE(DACRepeat::IsValid(-3));

    EXPECT_TRUE(DataFormat::IsValid(0));
    EXPECT_TRUE(DataFormat::IsValid(2));
    EXPECT_FALSE(DataFormat::IsValid(3));
    EXPECT_FALSE(DataFormat::IsValid(-1));
}

TEST(Enums, NamesAndValuesAreOrderedTogetherAndUnique) {
    std::set<std::string> names;
    std::set<int> values;
    for (size_t i = 0; i < DataFormat::count; i++) {
        names.insert(DataFormat::names()[i]);
        values.insert(DataFormat::values()[i]);
    }
    EXPECT_EQ(names.size(), DataFormat::count);
    EXPECT_EQ(values.size(), DataFormat::count);
    EXPECT_STREQ(DataFormat::names()[0], "WAV");
    EXPECT_STREQ(DataFormat::strings()[0], "wav");
}

// names() and strings() cache into function-local statics on first call. Repeat
// calls must hand back the same pointers, because callers store the char* and
// compare it later.
TEST(Enums, TheNameTablesAreBuiltOnceAndStayStable) {
    const char* const* first = DataFormat::names();
    const char* const* second = DataFormat::names();
    EXPECT_EQ(first, second);
    for (size_t i = 0; i < DataFormat::count; i++) {
        EXPECT_EQ(first[i], second[i]) << "index " << i;
    }
    EXPECT_NE(static_cast<const void*>(DataFormat::names()), static_cast<const void*>(DataFormat::strings()));
}

TEST(Enums, ImplicitConversionToTheUnderlyingEnumeratorWorks) {
    const DataFormat format = DataFormat::TDMS;
    switch (format) {
        case DataFormat::TDMS:
            SUCCEED();
            break;
        default:
            ADD_FAILURE() << "the implicit operator _enumerated did not fire";
    }
    EXPECT_EQ(format.value, DataFormat::TDMS);
}

// With the old member operator== this test did not compile at all: comparing two
// enums warned about the C++20 reversed-candidate ambiguity, and comparing one
// against a bare enumerator was a hard error.
TEST(Enums, EqualityComparesTheStoredValue) {
    DataFormat tdms = DataFormat::TDMS;
    DataFormat alsoTdms = DataFormat::TDMS;
    DataFormat wav = DataFormat::WAV;

    EXPECT_TRUE(tdms == alsoTdms);
    EXPECT_FALSE(tdms == wav);
    EXPECT_TRUE(tdms == DataFormat::TDMS);
    EXPECT_FALSE(tdms == DataFormat::WAV);

    const DataFormat frozen = DataFormat::TDMS;
    EXPECT_TRUE(frozen == alsoTdms);
    EXPECT_TRUE(frozen == DataFormat::TDMS);
    EXPECT_TRUE(DataFormat::TDMS == frozen) << "either operand order";
    EXPECT_TRUE(tdms != wav);
    EXPECT_FALSE(tdms != alsoTdms);
}

// The generated types carry no operator== of their own; comparison goes through
// the implicit conversion to _enumerated and the built-in operator. That is what
// keeps every combination of const-ness and operand order unambiguous - a member
// operator ties with the built-in one for the enum-vs-enumerator case, whichever
// way its const-ness is declared.
TEST(Enums, EveryCombinationOfOperandsIsComparable) {
    using Enumerated = DataFormat::_enumerated;
    static_assert(IsComparable<DataFormat&, DataFormat&>::value);
    static_assert(IsComparable<const DataFormat&, const DataFormat&>::value);
    static_assert(IsComparable<DataFormat&, const DataFormat&>::value);
    static_assert(IsComparable<DataFormat&, Enumerated>::value);
    static_assert(IsComparable<const DataFormat&, Enumerated>::value);
    static_assert(IsComparable<Enumerated, DataFormat&>::value);
    static_assert(IsComparable<Enumerated, const DataFormat&>::value);
    SUCCEED();
}

// A value inside the enum's value range but matching no enumerator is
// well-formed - for a three-enumerator enum the range runs to 3 - and the three
// accessors then disagree: name() returns NULL, which is UB for any caller that
// wraps it in a std::string (toJson and getValue both do), while to_string()
// throws. 3 is used rather than something like 99 on purpose: a value outside
// the range is itself undefined behaviour, so the test would be testing the
// test.
TEST(Enums, AnUndeclaredValueMakesNameReturnNullAndToStringThrow) {
    ASSERT_FALSE(DataFormat::IsValid(3));
    const DataFormat undeclared = static_cast<DataFormat::_enumerated>(3);
    EXPECT_EQ(undeclared.name(), nullptr);
    EXPECT_THROW(undeclared.to_string(), std::invalid_argument);
}
